In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('CKD.csv')
dataset=pd.get_dummies(dataset,drop_first=True,dtype='int')
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [3]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [4]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [5]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
x_train=scx.fit_transform(x_train)
x_test=scx.transform(x_test)

In [7]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV
param_grid={'solver':['liblinear','saga','lbfgs','newton_cg','newton-cholesky', 'sag'],'penalty':['l1','l2','elasticnet', None]}
grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
65 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _check_solver(self.solver, self.penalty, self.dua

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['liblinear', 'saga', 'lbfgs', 'newton_cg',
                                    'newton-cholesky', 'sag']},
             scoring='f1_weighted', verbose=3)

In [8]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

In [9]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)
print(cm)

[[45  0]
 [ 1 74]]


In [10]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



In [11]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print('The f1_macro value for the best parameters {}'.format(grid.best_params_),f1_macro)

The f1_macro value for the best parameters {'penalty': 'l2', 'solver': 'lbfgs'} 0.9916844900066377


In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [13]:
table=pd.DataFrame.from_dict(result)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.008466      0.004244         0.016261        0.003153   
1        0.029696      0.002284         0.013270        0.004099   
2        0.002343      0.002150         0.000000        0.000000   
3        0.003135      0.003299         0.000000        0.000000   
4        0.002680      0.002918         0.000000        0.000000   
5        0.001821      0.003642         0.000000        0.000000   
6        0.005578      0.001504         0.012349        0.001971   
7        0.018902      0.004114         0.011456        0.003202   
8        0.025499      0.003542         0.012836        0.001971   
9        0.001289      0.001042         0.000000        0.000000   
10       0.033763      0.012171         0.012109        0.002584   
11       0.023459      0.002351         0.012017        0.004385   
12       0.000989      0.001150         0.000000        0.000000   
13       0.002040      0.001358         0.000000        0.000000   
14       0.000900      0.001800         0.000000        0.000000   
15       0.000703      0.001405         0.000000        0.000000   
16       0.001423      0.002556         0.000000        0.000000   
17       0.000000      0.000000         0.000000        0.000000   
18       0.001807      0.003130         0.000000        0.000000   
19       0.021537      0.009821         0.012635        0.007324   
20       0.016065      0.011730         0.010839        0.001736   
21       0.001682      0.001173         0.000000        0.000000   
22       0.023189      0.005410         0.010424        0.001450   
23       0.018869      0.001472         0.004848        0.003667   

   param_penalty     param_solver  \
0             l1        liblinear   
1             l1             saga   
2             l1            lbfgs   
3             l1        newton_cg   
4             l1  newton-cholesky   
5             l1              sag   
6             l2        liblinear   
7             l2             saga   
8             l2            lbfgs   
9             l2        newton_cg   
10            l2  newton-cholesky   
11            l2              sag   
12    elasticnet        liblinear   
13    elasticnet             saga   
14    elasticnet            lbfgs   
15    elasticnet        newton_cg   
16    elasticnet  newton-cholesky   
17    elasticnet              sag   
18          None        liblinear   
19          None             saga   
20          None            lbfgs   
21          None        newton_cg   
22          None  newton-cholesky   
23          None              sag   

                                               params  split0_test_score  \
0            {'penalty': 'l1', 'solver': 'liblinear'}           1.000000   
1                 {'penalty': 'l1', 'solver': 'saga'}           1.000000   
2                {'penalty': 'l1', 'solver': 'lbfgs'}                NaN   
3            {'penalty': 'l1', 'solver': 'newton_cg'}                NaN   
4      {'penalty': 'l1', 'solver': 'newton-cholesky'}                NaN   
5                  {'penalty': 'l1', 'solver': 'sag'}                NaN   
6            {'penalty': 'l2', 'solver': 'liblinear'}           0.964572   
7                 {'penalty': 'l2', 'solver': 'saga'}           0.964572   
8                {'penalty': 'l2', 'solver': 'lbfgs'}           0.982221   
9            {'penalty': 'l2', 'solver': 'newton_cg'}                NaN   
10     {'penalty': 'l2', 'solver': 'newton-cholesky'}           0.982221   
11                 {'penalty': 'l2', 'solver': 'sag'}           0.982221   
12   {'penalty': 'elasticnet', 'solver': 'liblinear'}                NaN   
13        {'penalty': 'elasticnet', 'solver': 'saga'}                NaN   
14       {'penalty': 'elasticnet', 'solver': 'lbfgs'}                NaN   
15   {'penalty': 'elasticnet', 'solver': 'newton_cg'}                NaN   
16  {'penalty': 'elasticnet', 'solver': 'newton-ch...                NaN   
17       

In [14]:
import pickle

In [15]:
preinput=scx.transform([[24,80,3,1,2,141.2,22,0.6,120,4.1,11,50,5897,5.2,1,0,0,1,0,1,0,1,1,0,1,0,0]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.72886894e+00,  2.65347207e-01,  1.75677722e+00,
         6.34738937e-01, -1.95836837e+00,  1.54903240e+00,
         3.17769838e+00, -1.32332439e+01,  5.29844604e+01,
        -3.07855702e+00, -3.41432638e+00, -3.49583526e+00,
         7.23756025e+03,  1.28748158e+01,  1.89044188e+00,
        -4.55842306e-01, -1.35085807e-01,  3.91014785e-01,
        -1.99553072e+00,  2.99404170e+00, -2.29848186e-01,
         1.35902126e+00,  1.36977686e+00, -2.99739470e-01,
         5.06711710e-01, -5.12292337e-01, -4.38529010e-01]])

In [16]:
filename='final_model_on_logreg_diseasepredict.sav'
filename1='scx.pkl'
pickle.dump(grid,open(filename,'wb'))
pickle.dump(scx,open(filename1,'wb'))

In [17]:
loaded_model=pickle.load(open('final_model_on_logreg_diseasepredict.sav','rb'))
scx=pickle.load(open('scx.pkl','rb'))
result1=loaded_model.predict(preinput)
result1

array([0])